import React from 'react';
import Link from 'next/link';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';

/**
 * Landing page, demonstrates Edge-OG with a live API call, architecture overview,
 * caching layer explanation, and quick-start snippet.
 */
export default function HomePage(): React.ReactElement {
    const demoUrl =
        '/api/og?template=blog-card&title=Edge-OG%3A+Dynamic+OG+Images+at+the+Edge&author=You&tag=Open+Graph&siteUrl=edge-og.vercel.app&accentColor=%236366f1';

    return (
        <div className="min-h-screen bg-slate-950 text-white">
            <Navbar />

            <main className="max-w-screen-xl mx-auto px-6 py-20 flex flex-col gap-24">
                {/* Hero */}
                <section className="flex flex-col items-center text-center gap-6">
                    <div className="inline-flex items-center gap-2 bg-indigo-950 border border-indigo-800 rounded-full px-4 py-1.5 text-indigo-300 text-sm">
                        ⚡ Runs on Vercel Edge Functions
                    </div>
                    <h1 className="text-5xl sm:text-6xl font-extrabold tracking-tight leading-tight max-w-3xl">
                        Dynamic OG images,{' '}
                        <span className="text-indigo-400">generated at the edge</span>
                    </h1>
                    <p className="text-xl text-slate-400 max-w-xl">
                        No headless browser. No third-party service. Just a URL, and your social cards
                        appear instantly, cached globally.
                    </p>
                    <div className="flex gap-4 flex-wrap justify-center">
                        <Link
                            href="/playground"
                            className="bg-indigo-600 hover:bg-indigo-500 transition-colors text-white font-semibold px-6 py-3 rounded-lg text-base"
                        >
                            Open Playground
                        </Link>
                        <a
                            href="/api/og?template=blog-card&title=Hello+World"
                            target="_blank"
                            rel="noopener noreferrer"
                            className="border border-slate-700 hover:border-slate-500 transition-colors text-slate-300 hover:text-white font-semibold px-6 py-3 rounded-lg text-base"
                        >
                            Try the API
                        </a>
                    </div>
                </section>

                {/* Live demo */}
                <section className="flex flex-col gap-6 items-center">
                    <h2 className="text-2xl font-bold text-center">Live API Demo</h2>
                    <p className="text-slate-400 text-sm text-center">
                        This image is generated by{' '}
                        <code className="text-indigo-300 font-mono bg-slate-900 px-1.5 py-0.5 rounded">
                            /api/og
                        </code>{' '}
                      , a real Edge Function call.
                    </p>
                    <div className="w-full max-w-3xl border border-slate-700 rounded-xl overflow-hidden shadow-2xl">
                        {/* eslint-disable-next-line @next/next/no-img-element */}
                        <img
                            src={demoUrl}
                            alt="Live OG card demo"
                            className="w-full h-auto"
                            style={{ aspectRatio: '1200/630' }}
                        />
                    </div>
                </section>

                {/* Architecture diagram */}
                <section className="flex flex-col gap-8">
                    <h2 className="text-2xl font-bold text-center">How It Works</h2>
                    <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
                        {[
                            { label: 'JSX Template', sub: 'Define your card in React' },
                            { label: 'Satori', sub: 'JSX → SVG' },
                            { label: 'resvg-wasm', sub: 'SVG → PNG' },
                        ].map((box, i, arr) => (
                            <React.Fragment key={box.label}>
                                <div className="flex flex-col items-center gap-2 bg-slate-900 border border-slate-700 rounded-xl px-8 py-6 min-w-[160px] text-center">
                                    <span className="font-semibold text-white">{box.label}</span>
                                    <span className="text-xs text-slate-500">{box.sub}</span>
                                </div>
                                {i < arr.length - 1 && (
                                    <span className="text-slate-600 text-2xl hidden sm:block">→</span>
                                )}
                            </React.Fragment>
                        ))}
                    </div>
                </section>

                {/* Caching layers */}
                <section className="flex flex-col gap-8">
                    <h2 className="text-2xl font-bold text-center">Two-Layer Cache</h2>
                    <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                        {[
                            {
                                step: '1',
                                title: 'Vercel CDN',
                                desc: 'Cache-Control headers instruct Vercel to serve identical requests globally without hitting the edge function.',
                            },
                            {
                                step: '2',
                                title: 'Upstash Redis',
                                desc: 'Edge-compatible Redis stores generated PNGs as base64 with a 48-hour TTL. Cold starts regenerate automatically.',
                            },
                            {
                                step: '3',
                                title: 'WASM Singleton',
                                desc: 'resvg-wasm initialises once per edge worker lifetime, subsequent renders skip the 2s compile cost.',
                            },
                        ].map((layer) => (
                            <div
                                key={layer.step}
                                className="bg-slate-900 border border-slate-700 rounded-xl p-6 flex flex-col gap-3"
                            >
                                <div className="w-8 h-8 bg-indigo-600 rounded-full flex items-center justify-center text-sm font-bold shrink-0">
                                    {layer.step}
                                </div>
                                <h3 className="font-semibold text-white">{layer.title}</h3>
                                <p className="text-sm text-slate-400 leading-relaxed">{layer.desc}</p>
                            </div>
                        ))}
                    </div>
                </section>

                {/* Quick start */}
                <section className="flex flex-col gap-6 items-center">
                    <h2 className="text-2xl font-bold text-center">Quick Start</h2>
                    <p className="text-slate-400 text-sm text-center max-w-lg">
                        Add one{' '}
                        <code className="text-indigo-300 font-mono bg-slate-900 px-1.5 py-0.5 rounded">
                            {'<meta>'}
                        </code>{' '}
                        tag to your page. That's it.
                    </p>
                    <pre className="bg-slate-900 border border-slate-700 rounded-xl p-6 text-sm font-mono text-slate-300 overflow-x-auto w-full max-w-2xl leading-relaxed">
                        <code>{`<!-- In your <head> -->
<meta
  property="og:image"
  content="https://your-app.vercel.app/api/og
    ?template=blog-card
    &title=My+Post+Title
    &author=Jane+Doe
    &tag=Tutorial"
/>`}</code>
                    </pre>
                    <Link
                        href="/playground"
                        className="bg-indigo-600 hover:bg-indigo-500 transition-colors text-white font-semibold px-6 py-3 rounded-lg"
                    >
                        Build your card in the Playground →
                    </Link>
                </section>
            </main>

            <Footer />
        </div>
    );
}
